using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Huske.UI
{
    public sealed partial class HuskeMissingMenu : DefaultWindow
    {
        public HuskeMissingMenu()
        {
            RobustXamlLoader.Load(this);
        }
    }
}
